### PR TITLE
update to python 3

### LINKED ISSUE #4: Build Fails
```
-- The C compiler identification is GNU 9.1.0
-- The CXX compiler identification is GNU 9.1.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using CATKIN_DEVEL_PREFIX: /home/acxz/.cache/yay/ros-melodic-eigen-stl-containers/src/build/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/melodic
-- This workspace overlays: /opt/ros/melodic
-- Found PythonInterp: /usr/bin/python2 (found suitable version "2.7.16", minimum required is "2") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python2
-- Using default Python package layout
-- Could NOT find PY_em (missing: PY_EM) 
CMake Error at /opt/ros/melodic/share/catkin/cmake/empy.cmake:29 (message):
  Unable to find either executable 'empy' or Python module 'em'...  try
  installing the package 'python-empy'
Call Stack (most recent call first):
  /opt/ros/melodic/share/catkin/cmake/all.cmake:163 (include)
  /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:20 (include)
  CMakeLists.txt:4 (find_package)


-- Configuring incomplete, errors occurred!
```

### PR DESCRIPTION
**Pull request by acxz**
Resolves #4

### CODE REVIEW

**Comment by jwhendy** [comment]
Hmmm. Will this be a problem for *all* packages using python2.7? I did
```
$ grep -R 'DPYTHON_BASENAME=-python2.7' */PKGBUILD
```
and get a lot of hits. Or is this something specific to this package which makes it require 3.7?

**Comment by acxz** [comment]
So far I have hit quite a lot packages that require 3.7 to build properly, I believe it may

**Comment by jwhendy** [comment]
I wonder why I didn't run into these before... Perhaps my `catkin` was not yet configured and still using `2.7`? In that case, perhaps it would only break if I didn't have the correct packages installed during building the package (which wants `3.7`) and using (which might globally still want `2.7`)? Not sure...

**Comment by jwhendy** [comment]
sorry for the delay -- just built, works great!

**Pull request merged**
